version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-gestao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gestao_alunos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: gestao-alunos-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:admin123@db:3306/gestao_alunos
      FIREBASE_API_KEY: sua_chave_aqui
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
