"""create tables

Revision ID: eebd747e34de
Revises: 
Create Date: 2025-05-25 16:03:32.292882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebd747e34de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=255), nullable=False),
    sa.Column('data_prova', sa.DateTime(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provas_id'), 'provas', ['id'], unique=False)
    op.create_table('trabalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabalhos_id'), 'trabalhos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trabalhos_id'), table_name='trabalhos')
    op.drop_table('trabalhos')
    op.drop_index(op.f('ix_provas_id'), table_name='provas')
    op.drop_table('provas')
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
